### PR TITLE
Initial working version

### PR DESCRIPTION
**Pull request by tokejepsen**
WOOT WOOT!

### CODE REVIEW

**Comment by tokejepsen** [comment]
Update done:)

**Comment by mottosso** [comment]
I'm still seeing at least one missing newline, are you sure your linter is working?

[PEP08, E302](http://pep8.readthedocs.org/en/latest/intro.html#error-codes)
- https://github.com/tokejepsen/pyblish-hiero/blob/5ca468e2ed7471d7e38532ce39b00d48e3f04726/pyblish_hiero/lib.py#L142

**Comment by tokejepsen** [comment]
> are you sure your linter is working?

Not using any linting, and it was super annoying and flagging stuff I didn't need to worry about. Will have a look at enabling it again.

**Comment by mottosso** [comment]
> and it was super annoying and flagging stuff I didn't need to worry about.

Made me chuckle. :)

It's for your own good, and for everyone else's.

**Comment by tokejepsen** [comment]
can't seem to get the linting to work properly, so I hope this is alright.

**Comment by mottosso** [comment]
Looks good, thanks!

**Pull request merged**
