### PR TITLE
working version of pyblish-base 1.4 upgrade

### PR DESCRIPTION
**Pull request by tokejepsen**
Having problems getting this to work. Getting this error;

```

K:\development\tools\pyblish>set PYTHONPATH=K:\development\tools\pyblish\pyblish
-base;K:\development\tools\pyblish\pyblish-qml;K:\development\tools\pyblish\pyth
on-qt5

K:\development\tools\pyblish>cd /D K:\development\tools\pyblish\../python/Python
27

K:\development\tools\python\Python27>python -m pyblish_qml
Starting Pyblish..
Spent 436.00 ms creating the application
Listening on 127.0.0.1:9090
Entering state: "hidden"
Entering state: "ready"
Entering state: "clean"
Entering state: "alive"
Finding available port..
Distributing new port 9001
Settings:
  WindowTitle = Pyblish (Nuke)
  HeartbeatInterval = 60
  WindowPosition = [100, 100]
  ContextLabel = Nuke
  WindowSize = [430, 600]
Entering state: "visible"
Entering state: "initialising"
Traceback (most recent call last):
  File "K:\development\tools\pyblish\pyblish-qml\pyblish_qml\app.py", line 172,
in show
    self.controller.reset()
  File "K:\development\tools\pyblish\pyblish-qml\pyblish_qml\control.py", line 6
10, in reset
    stats = {"requestCount": self.host.stats()["totalRequestCount"]}
  File "K:\development\tools\python\Python27\lib\xmlrpclib.py", line 1233, in __
call__
    return self.__send(self.__name, args)
  File "K:\development\tools\python\Python27\lib\xmlrpclib.py", line 1591, in __
request
    verbose=self.__verbose
  File "K:\development\tools\python\Python27\lib\xmlrpclib.py", line 1273, in re
quest
    return self.single_request(host, handler, request_body, verbose)
  File "K:\development\tools\python\Python27\lib\xmlrpclib.py", line 1306, in si
ngle_request
    return self.parse_response(response)
  File "K:\development\tools\python\Python27\lib\xmlrpclib.py", line 1482, in pa
rse_response
    return u.close()
  File "K:\development\tools\python\Python27\lib\xmlrpclib.py", line 794, in clo
se
    raise Fault(**self._stack[0])
xmlrpclib.Fault: <Fault 1: "<type 'exceptions.NotImplementedError'>:method not i
mplemented">
```

### CODE REVIEW

**Comment by mottosso** [comment]
Odd! How is the Qml being shown from Hiero, or how is the RPC server started?

**Comment by tokejepsen** [comment]
I'm running `pyblish-qml` in a separate terminal with `python -m pyblish_qml`.

Do you know what the error might be about?

**Comment by mottosso** [comment]
Oh, well I assumed the error appeared when using it with Hiero. The window title says "Nuke". Does this appear right away? In that case, try running the latest release, as opposed to the latest commit?

**Comment by tokejepsen** [comment]
> The window title says "Nuke". Does this appear right away?

That's the direction I need to head in:) Thought there was some magic I didn't understand, but its here; https://github.com/pyblish/pyblish-qml/blob/0c6e2d35702cd21f6d56ec06706d5152e5aeac7b/pyblish_qml/host.py#L262

**Comment by tokejepsen** [comment]
Problem is that you can import the `nuke` module in Hiero, and you can import `hiero` in Nuke :S

**Comment by tokejepsen** [comment]
Got a working version with this PR on `pyblish-qml`: https://github.com/pyblish/pyblish-qml/pull/211

**Comment by tokejepsen** [comment]
Now there is a slight problem where you need to force the qt module to prefer `PySide` with `set QT_PREFERRED_BINDING=PySide`.
If you don't do this, you get an error;

```
QWidget: Must construct a QApplication before a QWidget
ModalMessage::setMinimumWidth not implemented for this Qt version!
```

Plus this messagebox, followed by an application crash:
capture

I could just reimplement the messagebox logic to use PySide instead of the Qt module, although less future proof.

**Comment by mottosso** [comment]
About the preferred binding; I'd expect this. Set it to `os.pathsep.join(["PySide", PyQt4])` in Nuke versions that only support Qt 4, and the Qt 5 equivalents for newer ones.

Or if you'd like, to `PySide2;PySide` for both if PyQt is a problem.

**Comment by tokejepsen** [comment]
Since this is just to display information to the user, and I haven't heard about PySide2 for Nuke, I think I'm voting to just use the built-in PySide for now.

**Comment by tokejepsen** [comment]
This has been in production for a while now, and should be safe to merge.

**Comment by tokejepsen** [comment]
Any problems merging this?

**Comment by mottosso** [comment]
Hey Toke,

Are you asking me? I can't test this myself and trust you guys to know best.

**Comment by tokejepsen** [comment]
Alright :)

**Comment by tokejepsen** [comment]
Will need some rights to merge this :)

**Comment by mottosso** [comment]
Added. :)

**Pull request merged**
